# Server configuration
server:
  port: 8080
  host: "0.0.0.0"

# Provider configuration
provider:
  # Your provider API key from the Inferoute platform
  api_key: "test_key_tier2b"
  # URL of the central Inferoute system
  url: "http://192.168.0.36:80"
  # Type of provider (ollama, exolabs, etc.)
  provider_type: "ollama"
  # URL of the local LLM provider
  llm_url: "http://localhost:11434"

# NGROK configuration (will be overridden by code for now)
ngrok:
  url: "https://6a2f-2a02-c7c-a0c9-5000-127c-61ff-fe4b-7035.ngrok-free.app"