# Server configuration
server:
  port: 8090
  host: "0.0.0.0"

# Provider configuration
provider:
  # Your provider API key from the Inferoute platform
  api_key: "test_key_tier2b"
  # URL of the central Inferoute system
  url: "http://192.168.0.3:80"
  # Type of provider (ollama, exolabs, etc.)
  provider_type: "ollama"
  # URL of the local LLM provider
  llm_url: "http://localhost:11434"

# NGROK configuration (will be overridden by code for now)
ngrok:
  url: "https://74a6-2a02-c7c-a0c9-5000-127c-61ff-fe4b-7035.ngrok-free.app"

# Logging configuration
logging:
  # Log level: debug, info, warn, error
  level: "info"
  # Log directory (defaults to ~/.local/state/inferoute/log if empty)
  log_dir: ""
  # Maximum size of log files in megabytes before rotation
  max_size: 100
  # Maximum number of old log files to retain
  max_backups: 5
  # Maximum number of days to retain old log files
  max_age: 30 