package setup

var waitQuotes = []string{
	`"A computer would deserve to be called intelligent if it could deceive a human into believing that it was human." — Alan Turing`,
	`"As soon as it works, no one calls it AI anymore." — John McCarthy`,
	`"Artificial intelligence is the science of making machines do things that would require intelligence if done by men." — Marvin Minsky`,
	`"A year spent in artificial intelligence is enough to make one believe in God." — Alan Perlis`,
	`"Machine intelligence is the last invention that humanity will ever need to make." — Nick Bostrom`,
	`"Artificial intelligence is the new electricity." — Andrew Ng`,
	`"AI is probably the most important thing humanity has ever worked on—more profound than electricity or fire." — Sundar Pichai`,
	`"AI will not replace humans, but humans who use AI will replace those who don't." — Karim R. Lakhani`,
	`"Artificial intelligence, deep learning, machine learning—whatever you're doing, if you don't understand it, learn it. Because otherwise you're going to be a dinosaur within three years." — Mark Cuban`,
	`"We are witnessing the democratization of AI, where every industry, company, and individual can leverage its power." — Satya Nadella`,
	`"The ultimate search engine would understand everything on the web. It would understand exactly what you wanted, and it would give you the right thing. We're nowhere near doing that now. However, we can get incrementally closer to that, and that is basically what we work on." — Larry Page`,
	`"The purpose of AI is to amplify human ingenuity, not replace it." — Satya Nadella`,
	`"Our intelligence is what makes us human, and AI is an extension of that quality." — Yann LeCun`,
	`"Instead of artificial intelligence, I think we'll augment our intelligence." — Ginni Rometty`,
	`"Everything that civilization has to offer is a product of human intelligence; we cannot predict what we might achieve when this intelligence is magnified by the tools AI may provide." — Stephen Hawking`,
	`"The question is not whether machines can think, but whether people will let them." — Isaac Asimov`,
	`"By 2029, computers will have emotional intelligence and be as convincing as people." — Ray Kurzweil`,
	`"The development of full artificial intelligence could spell the end of the human race." — Stephen Hawking`,
	`"With artificial intelligence, we are summoning the demon." — Elon Musk`,
	`"The real risk with AI isn't malice, but competence. A superintelligent AI will be extremely good at accomplishing its goals, and if those goals aren't aligned with ours, we're in trouble." — Stephen Hawking`,
	`"By far, the greatest danger of Artificial Intelligence is that people conclude too early that they understand it." — Eliezer Yudkowsky`,
	`"I am in the camp that is concerned about super intelligence." — Bill Gates`,
	`"AI doesn't have to be evil to destroy humanity—if AI has a goal and humanity just happens to be in the way, it will destroy humanity as a matter of course without even thinking about it, no hard feelings." — Elon Musk`,
	`"AI will probably most likely lead to the end of the world, but in the meantime, there'll be great companies." — Sam Altman`,
	`"The question of whether a computer can think is no more interesting than the question of whether a submarine can swim." — Edsger W. Dijkstra`,
	`"It's not artificial intelligence I'm worried about, it's human stupidity." — Neil Jacobstein`,
	`"Before we work on artificial intelligence, why don't we do something about natural stupidity?" — Steve Polyak`,
	`"Forget artificial intelligence—in the brave new world of big data, it's artificial idiocy we should be looking out for." — Tom Chatfield`,
	`"Some people worry that artificial intelligence will make us feel inferior, but then, anybody in his right mind should have an inferiority complex every time he looks at a flower." — Alan Kay`,
}
