name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # This is required for creating releases and uploading assets

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build binaries
        run: |
          # Create build directory
          mkdir -p build
          
          # Build for Linux amd64
          GOOS=linux GOARCH=amd64 go build -o build/inferoute-client-linux-amd64 ./cmd
          
          # Build for Linux arm64
          GOOS=linux GOARCH=arm64 go build -o build/inferoute-client-linux-arm64 ./cmd
          
          # Build for macOS amd64 (Intel)
          GOOS=darwin GOARCH=amd64 go build -o build/inferoute-client-darwin-amd64 ./cmd
          
          # Build for macOS arm64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -o build/inferoute-client-darwin-arm64 ./cmd
          
          # Build for Windows amd64 (64-bit)
          GOOS=windows GOARCH=amd64 go build -o build/inferoute-client-windows-amd64.exe ./cmd
          
          # Build for Windows 386 (32-bit)
          GOOS=windows GOARCH=386 go build -o build/inferoute-client-windows-386.exe ./cmd
          
          # Create zip archives
          cd build
          zip -r inferoute-client-linux-amd64.zip inferoute-client-linux-amd64
          zip -r inferoute-client-linux-arm64.zip inferoute-client-linux-arm64
          zip -r inferoute-client-darwin-amd64.zip inferoute-client-darwin-amd64
          zip -r inferoute-client-darwin-arm64.zip inferoute-client-darwin-arm64
          zip -r inferoute-client-windows-amd64.zip inferoute-client-windows-amd64.exe
          zip -r inferoute-client-windows-386.zip inferoute-client-windows-386.exe
          cd ..
      
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/inferoute-client-linux-amd64.zip
            build/inferoute-client-linux-arm64.zip
            build/inferoute-client-darwin-amd64.zip
            build/inferoute-client-darwin-arm64.zip
            build/inferoute-client-windows-amd64.zip
            build/inferoute-client-windows-386.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
