name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # This is required for creating releases and uploading assets

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Debug - Print GitHub Context
        run: |
          echo "GitHub Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Permissions: ${{ toJSON(github.permissions) }}"
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Build binaries
        run: |
          # Create build directory
          mkdir -p build
          
          # Build for Linux amd64
          GOOS=linux GOARCH=amd64 go build -o build/inferoute-client-linux-amd64 ./cmd
          
          # Build for Linux arm64
          GOOS=linux GOARCH=arm64 go build -o build/inferoute-client-linux-arm64 ./cmd
          
          # Build for macOS amd64 (Intel)
          GOOS=darwin GOARCH=amd64 go build -o build/inferoute-client-darwin-amd64 ./cmd
          
          # Build for macOS arm64 (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -o build/inferoute-client-darwin-arm64 ./cmd
          
          # Create zip archives
          cd build
          zip -r inferoute-client-linux-amd64.zip inferoute-client-linux-amd64
          zip -r inferoute-client-linux-arm64.zip inferoute-client-linux-arm64
          zip -r inferoute-client-darwin-amd64.zip inferoute-client-darwin-amd64
          zip -r inferoute-client-darwin-arm64.zip inferoute-client-darwin-arm64
          cd ..
      
      - name: Debug - List Files
        run: |
          ls -la build/
          echo "Checking if files exist:"
          for file in build/inferoute-client-linux-amd64.zip build/inferoute-client-linux-arm64.zip build/inferoute-client-darwin-amd64.zip build/inferoute-client-darwin-arm64.zip; do
            if [ -f "$file" ]; then
              echo "$file exists"
            else
              echo "$file does not exist"
            fi
          done
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/inferoute-client-linux-amd64.zip
            build/inferoute-client-linux-arm64.zip
            build/inferoute-client-darwin-amd64.zip
            build/inferoute-client-darwin-arm64.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Debug - Release Status
        if: always()
        run: |
          echo "Release step status: ${{ steps.create_release.outcome }}"
          echo "Release step conclusion: ${{ steps.create_release.conclusion }}" 